import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/ToastProvider";


const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${poppins.variable}  h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <div>{children}</div>
        <ToastProvider/>
      </body>
    </html>
  );
}
